### ISSUE TITLE
Add support for parsing `unknown` type

### ISSUE THREAD

**Issue by Samuel-Lewis** [atlassian/extract-react-types#111]
Hello!
Currently, it seems there is no support for parsing the `unknown` type. This was introduce into [TS 3.0](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-0.html#new-unknown-top-type).

Is there any possibly of adding supprt for this? Thanks.

**Comment by danieldelcore** [comment]
Error log: 

```
Error: Missing converter for: TSUnknownKeyword
at convert (/opt/atlassian/pipelines/agent/build/node_modules/extract-react-types/dist/extract-react-types.cjs.dev.js:1785:25)
    at converters.TSTypeAnnotation (/opt/atlassian/pipelines/agent/build/node_modules/extract-react-types/dist/extract-react-types.cjs.dev.js:1332:10)
    at convert (/opt/atlassian/pipelines/agent/build/node_modules/extract-react-types/dist/extract-react-types.cjs.dev.js:1786:16)
    at converters.TSPropertySignature (/opt/atlassian/pipelines/agent/build/node_modules/extract-react-types/dist/extract-react-types.cjs.dev.js:1210:12)
    at convert (/opt/atlassian/pipelines/agent/build/node_modules/extract-react-types/dist/extract-react-types.cjs.dev.js:1786:16)
    at /opt/atlassian/pipelines/agent/build/node_modules/extract-react-types/dist/extract-react-types.cjs.dev.js:1326:14
    at Array.map (<anonymous>)

```

**Comment by Noviny** [comment]
This has been fixed
